# Generated by Django 4.2.6 on 2023-12-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_billingdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingdetail',
            name='address',
        ),
        migrations.RemoveField(
            model_name='billingdetail',
            name='country',
        ),
        migrations.RemoveField(
            model_name='billingdetail',
            name='optional_address',
        ),
        migrations.RemoveField(
            model_name='billingdetail',
            name='state',
        ),
        migrations.RemoveField(
            model_name='billingdetail',
            name='zip',
        ),
        migrations.AddField(
            model_name='register_user',
            name='address',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='register_user',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register_user',
            name='optional_address',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='register_user',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register_user',
            name='zip',
            field=models.IntegerField(null=True),
        ),
    ]
